# Generated by Django 3.2.7 on 2022-03-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='slag',
            new_name='slug',
        ),
    ]
